name: 'Qodana Composite'
description: 'Reusable Qodana workflow'

inputs: 
  qodana_token:
    description: 'Qodana API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Code Checkout
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
        fetch-depth: 0  # a full history is required for pull request analysis
      
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v2024.2.3
      with:
        pr-mode: false
        push-fixes: pull-request
      env:
        QODANA_TOKEN: ${{ inputs.qodana_token }}
